import { FormEvent, useEffect, useState } from "react";
const API = import.meta.env.VITE_API_URL ?? "http://localhost:8000";
type Stage = "planning" | "screenwriting" | "storyboarding" | "criticizing" | "voicing" | "codegen" | "validating" | "rendering" | "muxing" | "completed";
type Job = { id: string; status: string; stage: Stage; progress: number; topic: string; error?: string; video_url?: string; artifacts?: Record<string, string> };
const subjects = ["General", "Mathematics", "Computer Science", "Physics", "Chemistry", "Biology", "Economics", "History"];
const stages: { id: Stage; label: string }[] = [{ id: "planning", label: "Planning lesson" }, { id: "screenwriting", label: "Writing explanation" }, { id: "storyboarding", label: "Designing visuals" }, { id: "voicing", label: "Generating voice" }, { id: "codegen", label: "Building animation" }, { id: "rendering", label: "Rendering" }, { id: "muxing", label: "Finalizing" }];
export default function App() {
 const [topic, setTopic] = useState(""); const [subject, setSubject] = useState("General"); const [quality, setQuality] = useState("Medium"); const [voice, setVoice] = useState("teaching_assistant"); const [voiceover, setVoiceover] = useState(true); const [job, setJob] = useState<Job | null>(null); const [feedback, setFeedback] = useState(""); const [requestError, setRequestError] = useState(""); const [debug, setDebug] = useState<{ name: string; data: unknown } | null>(null);
 const working = !!job && job.status !== "completed" && job.status !== "failed";
 async function api<T>(path: string, options?: RequestInit): Promise<T> { let response: Response; try { response = await fetch(`${API}${path}`, options); } catch { throw new Error(`Cannot reach the API at ${API}. Confirm the FastAPI server is running.`); } if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.detail ?? `API request failed (${response.status}).`); } return response.json() as Promise<T>; }
 useEffect(() => { if (!working || !job) return; let active = true; const poll = () => api<Job>(`/api/lessons/${job.id}`).then(next => { if (active) { setJob(next); setRequestError(""); } }).catch(error => { if (!active) return; const message = error instanceof Error ? error.message : "Unable to check lesson status."; setRequestError(message); if (message === "Lesson not found") setJob(current => current ? { ...current, status: "failed", error: "This lesson is no longer available on the API. Generate a new lesson to try again." } : current); }); poll(); const timer = setInterval(poll, 1500); return () => { active = false; clearInterval(timer); }; }, [job?.id, working]);
 async function create(e: FormEvent) { e.preventDefault(); setRequestError(""); setDebug(null); try { setJob(await api<Job>("/api/lessons", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic, subject, quality, voice_preset: voice, use_voiceover: voiceover }) })); } catch (error) { setRequestError(error instanceof Error ? error.message : "Unable to create lesson."); } }
 async function regenerate() { if (!job || !feedback.trim()) return; setRequestError(""); try { setJob(await api<Job>(`/api/lessons/${job.id}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ feedback }) })); setFeedback(""); } catch (error) { setRequestError(error instanceof Error ? error.message : "Unable to regenerate lesson."); } }
 async function viewArtifact(name: string, path: string) { try { setDebug({ name, data: await api(path) }); } catch (error) { setRequestError(error instanceof Error ? error.message : "Unable to load artifact."); } }
 return <main><header><small>ONLYSTUDIES</small><h1>Make difficult ideas<br />feel visual.</h1><p>Generate explanation-led animated lessons.</p></header><section><form onSubmit={create}><label>What should we explain?<input required minLength={2} value={topic} onChange={e => setTopic(e.target.value)} placeholder="e.g. Physics of a bicycle" /></label><div className="grid"><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}>{subjects.map(x => <option key={x}>{x}</option>)}</select></label><label>Quality<select value={quality} onChange={e => setQuality(e.target.value)}>{["Low", "Medium", "High"].map(x => <option key={x}>{x}</option>)}</select></label><label>Voice<select disabled={!voiceover} value={voice} onChange={e => setVoice(e.target.value)}>{["teaching_assistant", "professor", "enthusiastic", "calm", "neutral"].map(x => <option key={x}>{x.replace("_", " ")}</option>)}</select></label></div><label className="toggle"><input type="checkbox" checked={voiceover} onChange={e => setVoiceover(e.target.checked)} />Include voiceover</label><button disabled={working}>{working ? "Creating lesson…" : "Generate lesson"}</button></form>{requestError && <pre>{requestError}</pre>}</section>{job && <section><strong className={job.status}>{job.status === "completed" ? "Lesson ready" : `Stage: ${job.stage}`}</strong><div className="stages">{stages.map((stage, index) => <span key={stage.id} className={job.stage === stage.id ? "active" : (job.progress > index / stages.length || job.status === "completed") ? "done" : ""}>{job.stage === stage.id ? "●" : (job.progress > index / stages.length || job.status === "completed") ? "✓" : "○"} {stage.label}</span>)}</div>{job.error && <pre>{job.error}</pre>}{job.artifacts && <div className="artifacts">{Object.entries(job.artifacts).map(([name, path]) => <button type="button" key={name} onClick={() => viewArtifact(name, path)}>View {name.replace("_", " ")}</button>)}</div>}{debug && <details open><summary>{debug.name}</summary><pre>{JSON.stringify(debug.data, null, 2)}</pre></details>}{job.status === "completed" && <><video controls src={`${API}${job.video_url}`} /><a href={`${API}${job.video_url}`}>Download MP4</a><label>Improve this lesson<textarea value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="For example: make the bicycle turn rather than only showing arrows." /></label><button onClick={regenerate}>Regenerate relevant stages</button></>}</section>}</main>;
}
