from typing import Protocol
from pydantic import BaseModel
class LLMProvider(Protocol):
    def generate_structured(self, *, system_prompt: str, user_prompt: str, schema: type[BaseModel]) -> BaseModel: ...
    def generate_text(self, *, system_prompt: str, user_prompt: str) -> str: ...
